# Self attention embedding table

Adding route to custom libraries

In [1]:
import sys
import os


dirname = os.path.abspath(os.path.join(os.getcwd(), "..", "..", "scripts/lib"))
sys.path.append(dirname)

## Importing libraries

In [2]:
import torch
import torch.nn as nn
from torch.nn import functional as F

from utils.compile import compileFolder
from utils.tokenizer import CharTokenizer, END_CHAR
from utils.datasets import TextChunksDataset, split_dataset, get_batch, estimate_loss

In [3]:
# This module helps to quickly save the weights and load them
from transformers import Module

## Setting Hyperparameters

In [4]:
# The max block size (also known as max context) [in tokens]
block_size = 8

# How much does the test/validation set represent of the total data
test_train_split_ratio = 0.1

# Number of embedding
n_embd = 32

# Device (gpu or cpu)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

## Setting up the data and other

In [5]:
# Importing the data
raw_data = compileFolder('tate')

# Creating the tokenizer
tokenizer = CharTokenizer(raw_data)

# Tokenizing and creating the dataset object
data = TextChunksDataset(raw_data, block_size, tokenizer)

In [6]:
train_data, test_data = split_dataset(data, 0.1)

## Implementation of the self attention block

We take almost the same structure as the base-embedding structure

> Note: starting from now, we're going to use `cuda` when available

In [7]:
class BigramLanguageModel(Module):
    def __init__(self, vocab_size: int | CharTokenizer | TextChunksDataset, n_embd, device=device, context_size=None):
        """
        If vocab_size is a Dataset with context_length, then no need to specify context_size
        """
        super().__init__()
        if context_size==None:
            if type(vocab_size)==TextChunksDataset:
                context_size = vocab_size.context_length
            else:
                raise Exception("You need to specify the context length")
        self.block_size = context_size
        self.device = device
        if type(vocab_size)==TextChunksDataset:
            vocab_size=len(vocab_size.tokenizer)
        elif type(vocab_size)==CharTokenizer:
            vocab_size=len(vocab_size)
        # each token has a probability distribution of appearing depending on the last token
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd, device=self.device)
        self.position_embedding_table = nn.Embedding(self.block_size, n_embd, device=self.device)
        self.lm_head = nn.Linear(n_embd, vocab_size, device=self.device)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_embd = self.token_embedding_table(idx) # (B,T,C)
        pos_embd = self.position_embedding_table(torch.arange(T, device=self.device)) # (T,C)
        x = tok_embd + pos_embd # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss=None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens: int):
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx[:,-self.block_size:])
            # focus only on the last time step
            logits = logits[:,-1,:]
            # apply softmax to get the probabilities
            probs = F.softmax(logits, dim=1)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled text to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
        

In [8]:
torch.manual_seed(89)
m = BigramLanguageModel(train_data, n_embd)
xb, yb = train_data[:10]
out = m(xb, yb)
print(tokenizer.decodeText(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0]))


LeL:havOnUnmEVLM:bRwFt dM0c?cDtLv-?oJ=?VaRJ7"2M20AM
fn8bFyZ:?m7N0na0wm'qKeL
8T?B?9!ib:6Zbp2A:%tsaM8


The result is random characters

## Training the model

In [9]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [10]:
batch_size = 32
num_epochs = 100

# verbose
show_loss_each_epoch = 500

def train(optimizer, num_epochs=num_epochs, loss_verbose_interval=show_loss_each_epoch):
    for steps in range(num_epochs):

        # sample a batch of data
        xb, yb = get_batch(train_data, batch_size)

        # evaluate the loss
        logits, loss = m(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        if (steps+1)%loss_verbose_interval==0:
            losses = estimate_loss(m, train_data, test_data, batch_size=batch_size)
            print(f"step {steps+1}: train loss {losses ['train']:.4f}, val loss {losses ['val']:.4f}")
    print('done!')

In [11]:
train(optimizer, 1500)

step 500: train loss 2.6314, val loss 2.7112
step 1000: train loss 2.5292, val loss 2.5621
step 1500: train loss 2.4844, val loss 2.5606
done!


In [12]:
print(tokenizer.decodeText(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0]))


hin theanigrst yo t joine whe, meat



s. n aacy thoreye thande.ove toutonce i k okered?
the m hoe c


Still the same result as the base model


## The mathematical trick to self attention

In [13]:
# Consider the following toy example

torch.manual_seed(198)
B, T, C = 4, 8, 2 # batch, time, channels
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

In [14]:
# We want x[b, t] = the mean of x[b, i] with i<=t
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)
xbow[0]

tensor([[ 0.3597,  0.1501],
        [ 0.3383,  0.7864],
        [ 0.3464,  0.5391],
        [ 0.0438,  0.4631],
        [ 0.0989,  0.1779],
        [ 0.2658,  0.2987],
        [-0.0105,  0.2283],
        [ 0.0798,  0.2066]])

In [15]:
# Second version (using Softmax)
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [16]:
xbow2 = wei @ x
xbow2[0]

tensor([[ 0.3597,  0.1501],
        [ 0.3383,  0.7864],
        [ 0.3464,  0.5391],
        [ 0.0438,  0.4631],
        [ 0.0989,  0.1779],
        [ 0.2658,  0.2987],
        [-0.0105,  0.2283],
        [ 0.0798,  0.2066]])

In [17]:
# We get the same tensor
torch.allclose(xbow, xbow2)

True

It is the same result

### Implementing an attention head
Now we're going to have a third version: the attention head.

We introduce first this new parameter: the head size

In [18]:
# Head size
head_size = 16

In [19]:
# Third version
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)


In [20]:
k = key(x) # (B, T, head_size)
q = query(x) # (B, T, head_size)
wei = q @ k.transpose(-2, -1) # (B, T, head_size) @ (B, head_size, T) --> (B, T, T)

tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

In [21]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4099, 0.5901, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3780, 0.2279, 0.3942, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1302, 0.5305, 0.1159, 0.2234, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2031, 0.0725, 0.2210, 0.0464, 0.4569, 0.0000, 0.0000, 0.0000],
        [0.1195, 0.0402, 0.1308, 0.3458, 0.3329, 0.0308, 0.0000, 0.0000],
        [0.0555, 0.5743, 0.0458, 0.0614, 0.0072, 0.2289, 0.0269, 0.0000],
        [0.1148, 0.0417, 0.1248, 0.1055, 0.2782, 0.0637, 0.1468, 0.1245]],
       grad_fn=<SelectBackward0>)

We can see that now the weights are not uniform in a row, rather have different values.

So we've implemented the keys, the queries, now we'll implement the values

In [22]:
value = nn.Linear(C, head_size, bias=False) # Same linear structure as the key and query linear models
v = value(x)
out = wei @ v

out.shape

torch.Size([4, 8, 16])

In [23]:
out[0,0] # The value of the first token for the first example

tensor([ 0.2252,  0.0816, -0.0861, -0.0980, -0.1490, -0.0824, -0.2695,  0.0722,
         0.1332, -0.1667, -0.0388, -0.2477, -0.0050,  0.1838, -0.0065,  0.1206],
       grad_fn=<SelectBackward0>)

For variance stability purposes, `wei` tensor needs to be divided by $\sqrt{\text{head\_size}}$

In [24]:
k = key(x) # (B, T, head_size)
q = query(x) # (B, T, head_size)
wei = q @ k.transpose(-2, -1) * (head_size**-0.5) # (B, T, head_size) @ (B, head_size, T) --> (B, T, T)

tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v

Let's create a `Head` class that implements a single head.

In [25]:
class Head(nn.Module):
    """One head of self attention"""

    def __init__(self, n_embd: int, head_size: int, block_size: int) -> None:
        super().__init__()
        self.head_size = head_size
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)   # (B, T, C)
        q = self.query(x) # (B, T, C)
        # Compute attention score ('affinities')
        wei = q @ k.transpose(-2, -1) * (self.head_size**-0.5) # (B, T, head_size) @ (B, head_size, T) --> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1)
        # Perform the weighted aggregation of the values
        v = self.value(x) # (B, T, C)
        out = wei @ v     # (B, T, T) @ (B, T, C) --> (B, T, C)
        return out        # (B, T, C)

Now let's redefine `BigramLanguageModel`

In [26]:
class BigramLanguageModel(Module):
    def __init__(self, vocab_size: int | CharTokenizer | TextChunksDataset, n_embd, device=device, context_size=None, head_size=16):
        """
        If vocab_size is a Dataset with context_length, then no need to specify context_size
        """
        super().__init__()
        if context_size==None:
            if type(vocab_size)==TextChunksDataset:
                context_size = vocab_size.context_length
            else:
                raise Exception("You need to specify the context length")
        self.block_size = context_size
        self.device = device
        if type(vocab_size)==TextChunksDataset:
            vocab_size=len(vocab_size.tokenizer)
        elif type(vocab_size)==CharTokenizer:
            vocab_size=len(vocab_size)
        # each token has a probability distribution of appearing depending on the last token
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd, device=self.device)
        self.position_embedding_table = nn.Embedding(self.block_size, n_embd, device=self.device)
        self.sa_head = Head(n_embd, n_embd, vocab_size)
        self.lm_head = nn.Linear(n_embd, vocab_size, device=self.device)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_embd = self.token_embedding_table(idx) # (B,T,C)
        pos_embd = self.position_embedding_table(torch.arange(T, device=self.device)) # (T,C)
        x = tok_embd + pos_embd # (B,T,C)
        x = self.sa_head(x)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss=None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens: int):
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx[:,-self.block_size:])
            # focus only on the last time step
            logits = logits[:,-1,:]
            # apply softmax to get the probabilities
            probs = F.softmax(logits, dim=1)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled text to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
        

In [27]:

m = BigramLanguageModel(train_data, n_embd)
xb, yb = train_data[:10]
out = m(xb, yb)
print(tokenizer.decodeText(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0]))


gth2C-riwP"wSCi0vOy%C…XsT5/"ftn1
8!!*aG*T8eP$4
mUxCcYTC1H/Wiy
Bl5wX
-6
*Q'*4W/5HC9XSq4CKC*…96>oC2Z…A


### The training

In [28]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-4)

In [31]:
train(optimizer, 5000)

step 500: train loss 2.5529, val loss 2.6305
step 1000: train loss 2.5604, val loss 2.5830
step 1500: train loss 2.5226, val loss 2.5723
step 2000: train loss 2.5229, val loss 2.5483
step 2500: train loss 2.5096, val loss 2.5469
step 3000: train loss 2.4930, val loss 2.5002
step 3500: train loss 2.4778, val loss 2.5315
step 4000: train loss 2.4406, val loss 2.5140
step 4500: train loss 2.4527, val loss 2.4918
step 5000: train loss 2.4408, val loss 2.4792
done!


In [32]:
print(tokenizer.decodeText(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0]))


I't
y.




Esiing mt thel, wigr
erandoe ined to ulifele ouere

Os fomd Qe't I d hemlbe ase ple kou u


Not yet very good!